services:
  db:
    image: postgres:17
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${GREENLIGHT_DB_NAME}
      POSTGRES_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      POSTGRES_DB: ${GREENLIGHT_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GREENLIGHT_DB_NAME}"]
      interval: 10s
      retries: 5
    ports:
      - "4546:5432"

  migrate:
    image: migrate/migrate:v4.16.2
    command:
      [
        "--path=/migrations",
        "-database",
        "postgres://${GREENLIGHT_DB_USERNAME}:${GREENLIGHT_DB_PASSWORD}@db:5432/${GREENLIGHT_DB_NAME}?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: [--port=4545, --env=production]
    env_file: .env
    # environment:
    #   GREENLIGHT_DB_PORT: ${GREENLIGHT_DB_PORT}
    #   GREENLIGHT_DB_USERNAME: ${GREENLIGHT_DB_USERNAME}
    #   GREENLIGHT_DB_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
    #   GREENLIGHT_DB_HOST: ${GREENLIGHT_DB_HOST}
    #   GREENLIGHT_DB_NAME: ${GREENLIGHT_DB_NAME}
    ports:
      - "4545:4545"
    restart: on-failure

volumes:
  db_data:
