services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${GREENLIGHT_DB_USERNAME}
      POSTGRES_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      POSTGRES_DB: ${GREENLIGHT_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GREENLIGHT_DB_NAME}"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  migrate:
    image: migrate/migrate:v4.16.2
    command:
      [
        "--path=/migrations",
        "-database",
        "postgres://${GREENLIGHT_DB_USERNAME}:${GREENLIGHT_DB_PASSWORD}@db:5432/${GREENLIGHT_DB_NAME}?sslmode=disable",
        "up",
      ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  app:
    image: ghcr.io/shortykevich/greenlight:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      GREENLIGHT_DB_HOST: db
      GREENLIGHT_DB_PORT: 5432
      GREENLIGHT_DB_USERNAME: ${GREENLIGHT_DB_USERNAME}
      GREENLIGHT_DB_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      GREENLIGHT_DB_NAME: ${GREENLIGHT_DB_NAME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
    command: ["--env=production", "--port=4545"]
    ports:
      - "4545:4545"
    restart: on-failure
    networks:
      - app-network

  caddy:
    image: caddy:2
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN_NAME}
      EMAIL: ${EMAIL}
    ports:
      - "6969:80"
      - "6967:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - app-network

volumes:
  caddy_data:
  caddy_config:
  db_data:

networks:
  app-network:
