services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${GREENLIGHT_DB_NAME}
      POSTGRES_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      POSTGRES_DB: ${GREENLIGHT_DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${GREENLIGHT_DB_NAME}"]
      interval: 10s
      retries: 5
    ports:
      - "4546:5432"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: [--port=4545, --env=production]
    environment:
      GREENLIGHT_DB_PORT: ${GREENLIGHT_DB_PORT}
      GREENLIGHT_DB_USERNAME: ${GREENLIGHT_DB_USERNAME}
      GREENLIGHT_DB_PASSWORD: ${GREENLIGHT_DB_PASSWORD}
      GREENLIGHT_DB_HOST: ${GREENLIGHT_DB_HOST}
      GREENLIGHT_DB_NAME: ${GREENLIGHT_DB_NAME}
    ports:
      - "4545:4545"
    restart: on-failure

volumes:
  db_data:
